(cl:defpackage smartcar_control-srv
  (:use )
  (:export
   "SETFLOAT"
   "<SETFLOAT-REQUEST>"
   "SETFLOAT-REQUEST"
   "<SETFLOAT-RESPONSE>"
   "SETFLOAT-RESPONSE"
   "SETINT"
   "<SETINT-REQUEST>"
   "SETINT-REQUEST"
   "<SETINT-RESPONSE>"
   "SETINT-RESPONSE"
   "SETPOINT"
   "<SETPOINT-REQUEST>"
   "SETPOINT-REQUEST"
   "<SETPOINT-RESPONSE>"
   "SETPOINT-RESPONSE"
   "SETSTRING"
   "<SETSTRING-REQUEST>"
   "SETSTRING-REQUEST"
   "<SETSTRING-RESPONSE>"
   "SETSTRING-RESPONSE"
  ))

