// Generated by gencpp from file smartcar_control/DriversInput.msg
// DO NOT EDIT!


#ifndef SMARTCAR_CONTROL_MESSAGE_DRIVERSINPUT_H
#define SMARTCAR_CONTROL_MESSAGE_DRIVERSINPUT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smartcar_control
{
template <class ContainerAllocator>
struct DriversInput_
{
  typedef DriversInput_<ContainerAllocator> Type;

  DriversInput_()
    : front_left_vel(0.0)
    , front_right_vel(0.0)
    , rear_left_vel(0.0)
    , rear_right_vel(0.0)
    , front_left_angle(0.0)
    , front_right_angle(0.0)
    , rear_left_angle(0.0)
    , rear_right_angle(0.0)  {
    }
  DriversInput_(const ContainerAllocator& _alloc)
    : front_left_vel(0.0)
    , front_right_vel(0.0)
    , rear_left_vel(0.0)
    , rear_right_vel(0.0)
    , front_left_angle(0.0)
    , front_right_angle(0.0)
    , rear_left_angle(0.0)
    , rear_right_angle(0.0)  {
  (void)_alloc;
    }



   typedef float _front_left_vel_type;
  _front_left_vel_type front_left_vel;

   typedef float _front_right_vel_type;
  _front_right_vel_type front_right_vel;

   typedef float _rear_left_vel_type;
  _rear_left_vel_type rear_left_vel;

   typedef float _rear_right_vel_type;
  _rear_right_vel_type rear_right_vel;

   typedef float _front_left_angle_type;
  _front_left_angle_type front_left_angle;

   typedef float _front_right_angle_type;
  _front_right_angle_type front_right_angle;

   typedef float _rear_left_angle_type;
  _rear_left_angle_type rear_left_angle;

   typedef float _rear_right_angle_type;
  _rear_right_angle_type rear_right_angle;





  typedef boost::shared_ptr< ::smartcar_control::DriversInput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smartcar_control::DriversInput_<ContainerAllocator> const> ConstPtr;

}; // struct DriversInput_

typedef ::smartcar_control::DriversInput_<std::allocator<void> > DriversInput;

typedef boost::shared_ptr< ::smartcar_control::DriversInput > DriversInputPtr;
typedef boost::shared_ptr< ::smartcar_control::DriversInput const> DriversInputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smartcar_control::DriversInput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smartcar_control::DriversInput_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smartcar_control::DriversInput_<ContainerAllocator1> & lhs, const ::smartcar_control::DriversInput_<ContainerAllocator2> & rhs)
{
  return lhs.front_left_vel == rhs.front_left_vel &&
    lhs.front_right_vel == rhs.front_right_vel &&
    lhs.rear_left_vel == rhs.rear_left_vel &&
    lhs.rear_right_vel == rhs.rear_right_vel &&
    lhs.front_left_angle == rhs.front_left_angle &&
    lhs.front_right_angle == rhs.front_right_angle &&
    lhs.rear_left_angle == rhs.rear_left_angle &&
    lhs.rear_right_angle == rhs.rear_right_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smartcar_control::DriversInput_<ContainerAllocator1> & lhs, const ::smartcar_control::DriversInput_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smartcar_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smartcar_control::DriversInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smartcar_control::DriversInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smartcar_control::DriversInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smartcar_control::DriversInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smartcar_control::DriversInput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smartcar_control::DriversInput_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smartcar_control::DriversInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0abe91c43e477d202ad7b132d7fe2c7e";
  }

  static const char* value(const ::smartcar_control::DriversInput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0abe91c43e477d20ULL;
  static const uint64_t static_value2 = 0x2ad7b132d7fe2c7eULL;
};

template<class ContainerAllocator>
struct DataType< ::smartcar_control::DriversInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smartcar_control/DriversInput";
  }

  static const char* value(const ::smartcar_control::DriversInput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smartcar_control::DriversInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 front_left_vel\n"
"float32 front_right_vel\n"
"float32 rear_left_vel\n"
"float32 rear_right_vel\n"
"float32 front_left_angle\n"
"float32 front_right_angle\n"
"float32 rear_left_angle\n"
"float32 rear_right_angle\n"
;
  }

  static const char* value(const ::smartcar_control::DriversInput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smartcar_control::DriversInput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.front_left_vel);
      stream.next(m.front_right_vel);
      stream.next(m.rear_left_vel);
      stream.next(m.rear_right_vel);
      stream.next(m.front_left_angle);
      stream.next(m.front_right_angle);
      stream.next(m.rear_left_angle);
      stream.next(m.rear_right_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DriversInput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smartcar_control::DriversInput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smartcar_control::DriversInput_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "front_left_vel: ";
    Printer<float>::stream(s, indent + "  ", v.front_left_vel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "front_right_vel: ";
    Printer<float>::stream(s, indent + "  ", v.front_right_vel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rear_left_vel: ";
    Printer<float>::stream(s, indent + "  ", v.rear_left_vel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rear_right_vel: ";
    Printer<float>::stream(s, indent + "  ", v.rear_right_vel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "front_left_angle: ";
    Printer<float>::stream(s, indent + "  ", v.front_left_angle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "front_right_angle: ";
    Printer<float>::stream(s, indent + "  ", v.front_right_angle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rear_left_angle: ";
    Printer<float>::stream(s, indent + "  ", v.rear_left_angle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rear_right_angle: ";
    Printer<float>::stream(s, indent + "  ", v.rear_right_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMARTCAR_CONTROL_MESSAGE_DRIVERSINPUT_H
