// Generated by gencpp from file smartcar_control/SetFloat.msg
// DO NOT EDIT!


#ifndef SMARTCAR_CONTROL_MESSAGE_SETFLOAT_H
#define SMARTCAR_CONTROL_MESSAGE_SETFLOAT_H

#include <ros/service_traits.h>


#include <smartcar_control/SetFloatRequest.h>
#include <smartcar_control/SetFloatResponse.h>


namespace smartcar_control
{

struct SetFloat
{

typedef SetFloatRequest Request;
typedef SetFloatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFloat
} // namespace smartcar_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::smartcar_control::SetFloat > {
  static const char* value()
  {
    return "3f47c51e9da05852f0d7f484f9279955";
  }

  static const char* value(const ::smartcar_control::SetFloat&) { return value(); }
};

template<>
struct DataType< ::smartcar_control::SetFloat > {
  static const char* value()
  {
    return "smartcar_control/SetFloat";
  }

  static const char* value(const ::smartcar_control::SetFloat&) { return value(); }
};


// service_traits::MD5Sum< ::smartcar_control::SetFloatRequest> should match
// service_traits::MD5Sum< ::smartcar_control::SetFloat >
template<>
struct MD5Sum< ::smartcar_control::SetFloatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::smartcar_control::SetFloat >::value();
  }
  static const char* value(const ::smartcar_control::SetFloatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::smartcar_control::SetFloatRequest> should match
// service_traits::DataType< ::smartcar_control::SetFloat >
template<>
struct DataType< ::smartcar_control::SetFloatRequest>
{
  static const char* value()
  {
    return DataType< ::smartcar_control::SetFloat >::value();
  }
  static const char* value(const ::smartcar_control::SetFloatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::smartcar_control::SetFloatResponse> should match
// service_traits::MD5Sum< ::smartcar_control::SetFloat >
template<>
struct MD5Sum< ::smartcar_control::SetFloatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::smartcar_control::SetFloat >::value();
  }
  static const char* value(const ::smartcar_control::SetFloatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::smartcar_control::SetFloatResponse> should match
// service_traits::DataType< ::smartcar_control::SetFloat >
template<>
struct DataType< ::smartcar_control::SetFloatResponse>
{
  static const char* value()
  {
    return DataType< ::smartcar_control::SetFloat >::value();
  }
  static const char* value(const ::smartcar_control::SetFloatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SMARTCAR_CONTROL_MESSAGE_SETFLOAT_H
