// Generated by gencpp from file smartcar_control/SetInt.msg
// DO NOT EDIT!


#ifndef SMARTCAR_CONTROL_MESSAGE_SETINT_H
#define SMARTCAR_CONTROL_MESSAGE_SETINT_H

#include <ros/service_traits.h>


#include <smartcar_control/SetIntRequest.h>
#include <smartcar_control/SetIntResponse.h>


namespace smartcar_control
{

struct SetInt
{

typedef SetIntRequest Request;
typedef SetIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInt
} // namespace smartcar_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::smartcar_control::SetInt > {
  static const char* value()
  {
    return "41a6318c88ca9d75d7a585e2aa4ca6ea";
  }

  static const char* value(const ::smartcar_control::SetInt&) { return value(); }
};

template<>
struct DataType< ::smartcar_control::SetInt > {
  static const char* value()
  {
    return "smartcar_control/SetInt";
  }

  static const char* value(const ::smartcar_control::SetInt&) { return value(); }
};


// service_traits::MD5Sum< ::smartcar_control::SetIntRequest> should match
// service_traits::MD5Sum< ::smartcar_control::SetInt >
template<>
struct MD5Sum< ::smartcar_control::SetIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::smartcar_control::SetInt >::value();
  }
  static const char* value(const ::smartcar_control::SetIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::smartcar_control::SetIntRequest> should match
// service_traits::DataType< ::smartcar_control::SetInt >
template<>
struct DataType< ::smartcar_control::SetIntRequest>
{
  static const char* value()
  {
    return DataType< ::smartcar_control::SetInt >::value();
  }
  static const char* value(const ::smartcar_control::SetIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::smartcar_control::SetIntResponse> should match
// service_traits::MD5Sum< ::smartcar_control::SetInt >
template<>
struct MD5Sum< ::smartcar_control::SetIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::smartcar_control::SetInt >::value();
  }
  static const char* value(const ::smartcar_control::SetIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::smartcar_control::SetIntResponse> should match
// service_traits::DataType< ::smartcar_control::SetInt >
template<>
struct DataType< ::smartcar_control::SetIntResponse>
{
  static const char* value()
  {
    return DataType< ::smartcar_control::SetInt >::value();
  }
  static const char* value(const ::smartcar_control::SetIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SMARTCAR_CONTROL_MESSAGE_SETINT_H
