// Generated by gencpp from file smartcar_control/SetIntRequest.msg
// DO NOT EDIT!


#ifndef SMARTCAR_CONTROL_MESSAGE_SETINTREQUEST_H
#define SMARTCAR_CONTROL_MESSAGE_SETINTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smartcar_control
{
template <class ContainerAllocator>
struct SetIntRequest_
{
  typedef SetIntRequest_<ContainerAllocator> Type;

  SetIntRequest_()
    : data(0)  {
    }
  SetIntRequest_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef int32_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::smartcar_control::SetIntRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smartcar_control::SetIntRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetIntRequest_

typedef ::smartcar_control::SetIntRequest_<std::allocator<void> > SetIntRequest;

typedef boost::shared_ptr< ::smartcar_control::SetIntRequest > SetIntRequestPtr;
typedef boost::shared_ptr< ::smartcar_control::SetIntRequest const> SetIntRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smartcar_control::SetIntRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smartcar_control::SetIntRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smartcar_control::SetIntRequest_<ContainerAllocator1> & lhs, const ::smartcar_control::SetIntRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smartcar_control::SetIntRequest_<ContainerAllocator1> & lhs, const ::smartcar_control::SetIntRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smartcar_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smartcar_control::SetIntRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smartcar_control::SetIntRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smartcar_control::SetIntRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smartcar_control::SetIntRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smartcar_control::SetIntRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smartcar_control::SetIntRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smartcar_control::SetIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da5909fbe378aeaf85e547e830cc1bb7";
  }

  static const char* value(const ::smartcar_control::SetIntRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda5909fbe378aeafULL;
  static const uint64_t static_value2 = 0x85e547e830cc1bb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::smartcar_control::SetIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smartcar_control/SetIntRequest";
  }

  static const char* value(const ::smartcar_control::SetIntRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smartcar_control::SetIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 data\n"
;
  }

  static const char* value(const ::smartcar_control::SetIntRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smartcar_control::SetIntRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetIntRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smartcar_control::SetIntRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smartcar_control::SetIntRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    Printer<int32_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMARTCAR_CONTROL_MESSAGE_SETINTREQUEST_H
