// Generated by gencpp from file smartcar_control/SetPoint.msg
// DO NOT EDIT!


#ifndef SMARTCAR_CONTROL_MESSAGE_SETPOINT_H
#define SMARTCAR_CONTROL_MESSAGE_SETPOINT_H

#include <ros/service_traits.h>


#include <smartcar_control/SetPointRequest.h>
#include <smartcar_control/SetPointResponse.h>


namespace smartcar_control
{

struct SetPoint
{

typedef SetPointRequest Request;
typedef SetPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPoint
} // namespace smartcar_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::smartcar_control::SetPoint > {
  static const char* value()
  {
    return "3374a123f3f3fd3591258738a2b4096b";
  }

  static const char* value(const ::smartcar_control::SetPoint&) { return value(); }
};

template<>
struct DataType< ::smartcar_control::SetPoint > {
  static const char* value()
  {
    return "smartcar_control/SetPoint";
  }

  static const char* value(const ::smartcar_control::SetPoint&) { return value(); }
};


// service_traits::MD5Sum< ::smartcar_control::SetPointRequest> should match
// service_traits::MD5Sum< ::smartcar_control::SetPoint >
template<>
struct MD5Sum< ::smartcar_control::SetPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::smartcar_control::SetPoint >::value();
  }
  static const char* value(const ::smartcar_control::SetPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::smartcar_control::SetPointRequest> should match
// service_traits::DataType< ::smartcar_control::SetPoint >
template<>
struct DataType< ::smartcar_control::SetPointRequest>
{
  static const char* value()
  {
    return DataType< ::smartcar_control::SetPoint >::value();
  }
  static const char* value(const ::smartcar_control::SetPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::smartcar_control::SetPointResponse> should match
// service_traits::MD5Sum< ::smartcar_control::SetPoint >
template<>
struct MD5Sum< ::smartcar_control::SetPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::smartcar_control::SetPoint >::value();
  }
  static const char* value(const ::smartcar_control::SetPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::smartcar_control::SetPointResponse> should match
// service_traits::DataType< ::smartcar_control::SetPoint >
template<>
struct DataType< ::smartcar_control::SetPointResponse>
{
  static const char* value()
  {
    return DataType< ::smartcar_control::SetPoint >::value();
  }
  static const char* value(const ::smartcar_control::SetPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SMARTCAR_CONTROL_MESSAGE_SETPOINT_H
