// Generated by gencpp from file smartcar_control/SetString.msg
// DO NOT EDIT!


#ifndef SMARTCAR_CONTROL_MESSAGE_SETSTRING_H
#define SMARTCAR_CONTROL_MESSAGE_SETSTRING_H

#include <ros/service_traits.h>


#include <smartcar_control/SetStringRequest.h>
#include <smartcar_control/SetStringResponse.h>


namespace smartcar_control
{

struct SetString
{

typedef SetStringRequest Request;
typedef SetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetString
} // namespace smartcar_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::smartcar_control::SetString > {
  static const char* value()
  {
    return "546971982e3fbbd5a41e60fb6432e357";
  }

  static const char* value(const ::smartcar_control::SetString&) { return value(); }
};

template<>
struct DataType< ::smartcar_control::SetString > {
  static const char* value()
  {
    return "smartcar_control/SetString";
  }

  static const char* value(const ::smartcar_control::SetString&) { return value(); }
};


// service_traits::MD5Sum< ::smartcar_control::SetStringRequest> should match
// service_traits::MD5Sum< ::smartcar_control::SetString >
template<>
struct MD5Sum< ::smartcar_control::SetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::smartcar_control::SetString >::value();
  }
  static const char* value(const ::smartcar_control::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::smartcar_control::SetStringRequest> should match
// service_traits::DataType< ::smartcar_control::SetString >
template<>
struct DataType< ::smartcar_control::SetStringRequest>
{
  static const char* value()
  {
    return DataType< ::smartcar_control::SetString >::value();
  }
  static const char* value(const ::smartcar_control::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::smartcar_control::SetStringResponse> should match
// service_traits::MD5Sum< ::smartcar_control::SetString >
template<>
struct MD5Sum< ::smartcar_control::SetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::smartcar_control::SetString >::value();
  }
  static const char* value(const ::smartcar_control::SetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::smartcar_control::SetStringResponse> should match
// service_traits::DataType< ::smartcar_control::SetString >
template<>
struct DataType< ::smartcar_control::SetStringResponse>
{
  static const char* value()
  {
    return DataType< ::smartcar_control::SetString >::value();
  }
  static const char* value(const ::smartcar_control::SetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SMARTCAR_CONTROL_MESSAGE_SETSTRING_H
