// Generated by gencpp from file smartcar_control/State.msg
// DO NOT EDIT!


#ifndef SMARTCAR_CONTROL_MESSAGE_STATE_H
#define SMARTCAR_CONTROL_MESSAGE_STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smartcar_control
{
template <class ContainerAllocator>
struct State_
{
  typedef State_<ContainerAllocator> Type;

  State_()
    : code(0)
    , name()  {
    }
  State_(const ContainerAllocator& _alloc)
    : code(0)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _code_type;
  _code_type code;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::smartcar_control::State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smartcar_control::State_<ContainerAllocator> const> ConstPtr;

}; // struct State_

typedef ::smartcar_control::State_<std::allocator<void> > State;

typedef boost::shared_ptr< ::smartcar_control::State > StatePtr;
typedef boost::shared_ptr< ::smartcar_control::State const> StateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smartcar_control::State_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smartcar_control::State_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smartcar_control::State_<ContainerAllocator1> & lhs, const ::smartcar_control::State_<ContainerAllocator2> & rhs)
{
  return lhs.code == rhs.code &&
    lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smartcar_control::State_<ContainerAllocator1> & lhs, const ::smartcar_control::State_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smartcar_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smartcar_control::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smartcar_control::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smartcar_control::State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smartcar_control::State_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smartcar_control::State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smartcar_control::State_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smartcar_control::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6945e95f8a0c81d7c5ff2efa0627e942";
  }

  static const char* value(const ::smartcar_control::State_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6945e95f8a0c81d7ULL;
  static const uint64_t static_value2 = 0xc5ff2efa0627e942ULL;
};

template<class ContainerAllocator>
struct DataType< ::smartcar_control::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smartcar_control/State";
  }

  static const char* value(const ::smartcar_control::State_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smartcar_control::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 code\n"
"string name\n"
;
  }

  static const char* value(const ::smartcar_control::State_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smartcar_control::State_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.code);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct State_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smartcar_control::State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smartcar_control::State_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.code);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMARTCAR_CONTROL_MESSAGE_STATE_H
