// Generated by gencpp from file smartcar_control/VelInput.msg
// DO NOT EDIT!


#ifndef SMARTCAR_CONTROL_MESSAGE_VELINPUT_H
#define SMARTCAR_CONTROL_MESSAGE_VELINPUT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smartcar_control
{
template <class ContainerAllocator>
struct VelInput_
{
  typedef VelInput_<ContainerAllocator> Type;

  VelInput_()
    : linear_vel(0.0)
    , angular_vel(0.0)  {
    }
  VelInput_(const ContainerAllocator& _alloc)
    : linear_vel(0.0)
    , angular_vel(0.0)  {
  (void)_alloc;
    }



   typedef float _linear_vel_type;
  _linear_vel_type linear_vel;

   typedef float _angular_vel_type;
  _angular_vel_type angular_vel;





  typedef boost::shared_ptr< ::smartcar_control::VelInput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smartcar_control::VelInput_<ContainerAllocator> const> ConstPtr;

}; // struct VelInput_

typedef ::smartcar_control::VelInput_<std::allocator<void> > VelInput;

typedef boost::shared_ptr< ::smartcar_control::VelInput > VelInputPtr;
typedef boost::shared_ptr< ::smartcar_control::VelInput const> VelInputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smartcar_control::VelInput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smartcar_control::VelInput_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smartcar_control::VelInput_<ContainerAllocator1> & lhs, const ::smartcar_control::VelInput_<ContainerAllocator2> & rhs)
{
  return lhs.linear_vel == rhs.linear_vel &&
    lhs.angular_vel == rhs.angular_vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smartcar_control::VelInput_<ContainerAllocator1> & lhs, const ::smartcar_control::VelInput_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smartcar_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smartcar_control::VelInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smartcar_control::VelInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smartcar_control::VelInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smartcar_control::VelInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smartcar_control::VelInput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smartcar_control::VelInput_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smartcar_control::VelInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4798be5c355a1844fc4eb8549a932b03";
  }

  static const char* value(const ::smartcar_control::VelInput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4798be5c355a1844ULL;
  static const uint64_t static_value2 = 0xfc4eb8549a932b03ULL;
};

template<class ContainerAllocator>
struct DataType< ::smartcar_control::VelInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smartcar_control/VelInput";
  }

  static const char* value(const ::smartcar_control::VelInput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smartcar_control::VelInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 linear_vel\n"
"float32 angular_vel\n"
;
  }

  static const char* value(const ::smartcar_control::VelInput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smartcar_control::VelInput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear_vel);
      stream.next(m.angular_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelInput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smartcar_control::VelInput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smartcar_control::VelInput_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "linear_vel: ";
    Printer<float>::stream(s, indent + "  ", v.linear_vel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angular_vel: ";
    Printer<float>::stream(s, indent + "  ", v.angular_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMARTCAR_CONTROL_MESSAGE_VELINPUT_H
